prompt: |
  请根据以下用户输入生成一个 JSON 对象，规则如下：
  - 如果是数学运算，使用格式：
    {"tool": "Calculator", "num1": <数字>, "num2": <数字>, "operator": "+|-|*|/"}
  - 如果是字符串操作，使用格式：
    {"tool": "StringTool", "operation": "length|uppercase|lowercase", "text": "<字符串>"}
  - 如果无法识别输入，返回：
    {"error": "不支持的输入格式"}
  请只返回 JSON 对象，不要包含其他文本。
  用户输入："{user_input}"